config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :movimentacaos
  resources :conta

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #pagina inicial
  root :to => "home#index"

  resources :conta do
       member do
  #       get 'short'
         put 'inativa'
       end
  #
  #     collection do
  #       get 'sold'
  #     end
  end
  
end

app/controllers/conta_controller.rb
class ContaController < ApplicationController
  before_action :set_contum, only: [:show, :edit, :update, :destroy, :inativa]

  # GET /conta
  # GET /conta.json
  def index
    @conta = Contum.all
  end

  # GET /conta/1
  # GET /conta/1.json
  def show
  end

  # GET /conta/new
  def new
    @contum = Contum.new
  end

  # GET /conta/1/edit
  def edit
  end

  # POST /conta
  # POST /conta.json
  def create
    @contum = Contum.new(contum_params)

    respond_to do |format|
      if @contum.save
        format.html { redirect_to @contum, notice: 'Conta criada com sucesso.' }
        format.json { render :show, status: :created, location: @contum }
      else
        format.html { render :new }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conta/1
  # PATCH/PUT /conta/1.json
  def update
    respond_to do |format|
      if @contum.update(contum_params)
        format.html { redirect_to @contum, notice: 'Conta alterada com sucesso.' }
        format.json { render :show, status: :ok, location: @contum }
      else
        format.html { render :edit }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conta/1
  # DELETE /conta/1.json
  def destroy
    @contum.destroy
    respond_to do |format|
      format.html { redirect_to conta_url, notice: 'Conta excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  def inativa
    @contum.set_inativo
    respond_to do |format|
      #byebug
      if @contum.update_columns(:ativo => false)
        format.html { redirect_to @contum, notice: 'Conta inativada com sucesso.' }
        format.json { render :show, status: :ok, location: @contum }
      else
        format.html { render :edit }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contum
      @contum = Contum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contum_params
      #byebug
      params.require(:contum).permit(:banco, :conta_corrent, :agencia, :saldo)
    end

end

app/helpers/conta_helper.rb
module ContaHelper
end

app/views/conta/_form.html.erb
<%= form_for(contum) do |f| %>
  <% if contum.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
      <h4><%= pluralize(contum.errors.count, "erro(s)") %> Não foi possível salvar conta:</h4>
      <ul>
      <% contum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-8">
      <%= f.label :banco, class: 'control-label' %><br>
      <%= f.text_field :banco, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <%= f.label :conta_corrent, class: 'control-label' %>
      <%= f.text_field :conta_corrent, class: 'form-control' %>
   </div>
  </div>
  
  <div class="row">
    <div class="form-group col-md-8">
      <%= f.label :agencia, class: 'control-label'%>
      <%= f.text_field :agencia,  class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <%= f.label :saldo, class: 'control-label' %>
    <%= f.text_field :saldo, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/conta/edit.html.erb
<h1>Editar Conta</h1>

<%= render 'form', contum: @contum %>

<%= link_to 'Visualizar', @contum %> |
<%= link_to 'Voltar', conta_path %>

app/views/conta/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Lista de Contas</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<% if notice or alert %>
<div class="alert alert-<%= alert ? 'warning' : 'success' %> alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p><p id="alert"><%= alert %></p>
</div>
<%end%>

<div class="col-md-12">
  <div class="panel panel-default">
      <div class="panel-heading">
          Contas
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
          <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Banco</th>
                      <th>Conta corrente</th>
                      <th>Agência</th>
                      <th>Saldo</th>
                      <th>Ativo</th>
                      <th colspan="3">Ação</th>
                    </tr>
                  </thead>
                 
                  <tbody>
                  <% @conta.each do |contum| %>
                    <tr>
                      <td><%= contum.banco %></td>
                      <td><%= contum.conta_corrent %></td>
                      <td><%= contum.agencia %></td>
                      <td><%= contum.saldo %></td>
                      <td><%= contum.ativo == true ? 'SIM': 'NÃO'%></td>
                      <td><%= link_to 'Visualizar', contum %></td>
                      <td><%= link_to 'Editar', edit_contum_path(contum) %></td>
                      <td><%= link_to 'Inativar', inativa_contum_path(contum), method: :put, data: { confirm: 'Desaja inativar?' }, class: 'btn btn-danger' if contum.ativo %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table> 
          </div>
    </div>  
  </div>    
</div>


<%= link_to 'Nova Conta', new_contum_path, class: 'btn btn-primary'  %>

app/views/conta/new.html.erb
<h1>Nova Conta</h1>

<%= render 'form', contum: @contum %>

<%= link_to 'Voltar', conta_path %>

app/views/conta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Banco:</strong>
  <%= @contum.banco %>
</p>

<p>
  <strong>Conta corrente:</strong>
  <%= @contum.conta_corrent %>
</p>

<p>
  <strong>Agência:</strong>
  <%= @contum.agencia %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @contum.saldo %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @contum.ativo == true ? 'SIM': 'NÃO' %>
</p>

<%= link_to 'Editar', edit_contum_path(@contum) %> |
<%= link_to 'Voltar', conta_path %>