config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :movimentacaos
  resources :conta

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #pagina inicial
  root :to => "home#index"

  resources :conta do
       member do
  #       get 'short'
         put 'inativa'
       end
  #
  #     collection do
  #       get 'sold'
  #     end
  end
  
end

app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
  belongs_to :conta, optional: true, class_name: Contum, foreign_key: :conta_id

  belongs_to :conta_receptora, optional: true, :class_name => "Contum"

  validates_presence_of :conta, :data_movimentacao, :valor

  def trata_movimentacao
  	#byebug
    if self.conta.nil?
        errors.add(:conta, :blank, message: "Informe a conta de origem!")
        return false
    end
  	if self.valor.to_int < 0
  		#byebug
  		errors.add(:valor, :blank, message: "não pode ser negativo!")
  		return false
  	end	

    @conta_origem = Contum.find_by(id: self.conta_id)
    
  	if self.tranferencia #errei a ortografia quando criei. ->transferencia#
      #byebug
      if self.conta_receptora_id.nil?
        errors.add(:conta_receptora_id, :blank, message: "Informe a conta para transferência!")
        return false
      end
  		
      @valor_total_debitado = @conta_origem.saldo - self.valor
      if self.data_movimentacao.wday >= 1 && self.data_movimentacao.wday <= 5
         if Time.current.hour >= 9 && Time.current.hour <= 18
            @valor_total_debitado = @valor_total_debitado - 5 #taxa de transferencia
         else
            @valor_total_debitado = @valor_total_debitado - 7 #taxa de transferencia 
         end       
      else
          @valor_total_debitado = @valor_total_debitado - 7 #taxa de transferencia
      end

      if self.valor > 1000
         @valor_total_debitado = @valor_total_debitado - 10 #taxa adicional
      end 

  		if not @conta_origem.update_columns(:saldo => @valor_total_debitado)
  			errors.add(:valor, :blank, message: "Não foi possível fazer transferência!")
  			return false
  		end
      @valor_total_creditado = self.conta_receptora.saldo + self.valor	
      if not self.conta_receptora.update_columns(:saldo => @valor_total_creditado)
        errors.add(:valor, :blank, message: "Não foi possível fazer transferência!")
        return false
      end
  	end

    if self.saque
      @valor_total = @conta_origem.saldo - self.valor
      #byebug
      if @conta_origem.saldo < self.valor
        errors.add(:valor, :blank, message: "Saldo não pode ficar negativo!")
        return false
      end
      if not @conta_origem.update_columns(:saldo => @valor_total)
        errors.add(:valor, :blank, message: "Não foi possível fazer o saque!")
        return false
      end 
    end

    if self.deposito
    #  if self.data_movimentacao.wday > 5  
    #    errors.add(:valor, :blank, message: "Depósito só é possível em dias úteis!")
    #    return false
    #  end
      @valor_total_deposito = @conta_origem.saldo + self.valor 
      if not @conta_origem.update_columns(:saldo => @valor_total_deposito)
        errors.add(:valor, :blank, message: "Não foi possível fazer o deposito!")
        return false
      end 
    end

  	return true	
  end
end

app/controllers/movimentacaos_controller.rb
class MovimentacaosController < ApplicationController
  before_action :set_movimentacao, only: [:show, :edit, :update, :destroy]

  # GET /movimentacaos
  # GET /movimentacaos.json
  def index
    @movimentacaos = Movimentacao.all
  end

  # GET /movimentacaos/1
  # GET /movimentacaos/1.json
  def show
  end

  # GET /movimentacaos/new
  def new
    @movimentacao = Movimentacao.new
  end

  # GET /movimentacaos/1/edit
  def edit
  end

  # POST /movimentacaos
  # POST /movimentacaos.json
  def create
    @movimentacao = Movimentacao.new(movimentacao_params)
    @movimentacao.data_movimentacao = Time.now

    #byebug
    respond_to do |format|
      if @movimentacao.trata_movimentacao && @movimentacao.save
        format.html { redirect_to @movimentacao, notice: 'Movimentacao criada com sucesso.' }
        format.json { render :show, status: :created, location: @movimentacao }
      else
        format.html { render :new }
        format.json { render json: @movimentacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimentacaos/1
  # PATCH/PUT /movimentacaos/1.json
  def update
    respond_to do |format|
      if @movimentacao.update(movimentacao_params)
        format.html { redirect_to @movimentacao, notice: 'Movimentacao atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @movimentacao }
      else
        format.html { render :edit }
        format.json { render json: @movimentacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimentacaos/1
  # DELETE /movimentacaos/1.json
  def destroy
    @movimentacao.destroy
    respond_to do |format|
      format.html { redirect_to movimentacaos_url, notice: 'Movimentacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimentacao
      @movimentacao = Movimentacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movimentacao_params
      params.require(:movimentacao).permit(:conta_id, :data_movimentacao, :tranferencia, :saque, :deposito, :valor, :conta_receptora_id)
    end
end

app/helpers/movimentacaos_helper.rb
module MovimentacaosHelper
end

app/views/movimentacaos/_form.html.erb
<%= form_for(movimentacao) do |f| %>
  <% if movimentacao.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(movimentacao.errors.count, "error") %> Não foi possível salvar a movimentação:</h4>
      <ul>
      <% movimentacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-8">
     <%= f.label :conta_id, class: 'control-label' %>
      <%= f.select :conta_id, 
        options_from_collection_for_select(Contum.all, :id, :full_name, movimentacao.conta_id), 
        { :include_blank => 'Selecione' }, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="field">
    <%= f.label :data_movimentacao %>
    <%= f.date_select :data_movimentacao, {disabled: true}%>
  </div>

  <div class="field">
    <%= f.label :tranferencia %>
    <%= f.check_box :tranferencia, {checked: true,:class => 'ck_transf' } %>
  </div>

  <div class="field">
    <%= f.label :saque %>
    <%= f.check_box :saque, { :class => 'ck_saque' } %>
  </div>

  <div class="field">
    <%= f.label :deposito %>
    <%= f.check_box :deposito, { :class => 'ck_deposito' } %>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
    <%= f.label :valor %>
    <%= f.text_field :valor, { :class => 'form-control' } %>
    </div>
  </div> 

  <div class="row conta_receptora">
    <div class="form-group col-md-8">
     <%= f.label :conta_receptora_id, class: 'control-label' %>
      <%= f.select :conta_receptora_id, 
        options_from_collection_for_select(Contum.all, :id, :full_name, movimentacao.conta_receptora_id), 
        { :include_blank => 'Selecione' }, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Salvar"%>
  </div>
<% end %>
<script type="text/javascript">
    $(document).ready(function() {
      $('.ck_transf').click(function() {
          if ($(this).is(':checked')) {
              $('.ck_saque').prop('checked', false);
              $('.ck_deposito').prop('checked', false);
          }
          $('.conta_receptora').show();
      });

      $('.ck_saque').click(function() {
          if ($(this).is(':checked')) {
              $('.ck_transf').prop('checked', false);
              $('.ck_deposito').prop('checked', false);
          }
          $('.conta_receptora').hide();
      });

      $('.ck_deposito').click(function() {
          if ($(this).is(':checked')) {
              $('.ck_saque').prop('checked', false);
              $('.ck_transf').prop('checked', false);
          }
          $('.conta_receptora').hide();
      });
});
     
</script>

app/views/movimentacaos/edit.html.erb
<h1>Editar Movimentação</h1>

<%= render 'form', movimentacao: @movimentacao %>

<%= link_to 'Visualizar', @movimentacao %> |
<%= link_to 'Voltar', movimentacaos_path %>

app/views/movimentacaos/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Movimentações</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<% if notice or alert %>
<div class="alert alert-<%= alert ? 'warning' : 'success' %> alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p><p id="alert"><%= alert %></p>
</div>
<%end%>

<div class="col-md-12">
  <div class="panel panel-default">
      <div class="panel-heading">
          Extrato
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>Conta</th>
                  <th>Data movimentação</th>
                  <th>Transferência</th>
                  <th>Saque</th>
                  <th>Depósito</th>
                  <th>Valor</th>
                </tr>
              </thead>

              <tbody>
                <% @movimentacaos.each do |movimentacao| %>
                  <tr>
                    <td><%= movimentacao.conta.full_name %></td>
                    <td><%= movimentacao.data_movimentacao.to_s(:custom_datetime) %></td>
                    <td align="center"><%= movimentacao.tranferencia == true ? 'X': ''%></td>
                    <td align="center"><%= movimentacao.saque == true ? 'X': ''%></td>
                    <td align="center"><%= movimentacao.deposito == true ? 'X': ''%></td>
                    <td><%= movimentacao.valor %></td>
                  </tr>
                <% end %>
              </tbody>
           </table> 
          </div>
    </div>  
  </div>    
</div>

<br>

<%= link_to 'Nova Movimentação', new_movimentacao_path, class: 'btn btn-primary' %>

app/views/movimentacaos/new.html.erb
<h1>Nova Movimentação</h1>

<%= render 'form', movimentacao: @movimentacao %>

<%= link_to 'Voltar', movimentacaos_path %>

app/views/movimentacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conta:</strong>
  <%= @movimentacao.conta.full_name %>
</p>

<p>
  <strong>Data movimentação:</strong>
  <%= @movimentacao.data_movimentacao.to_s(:custom_datetime) %>
</p>

<p>
  <strong>Transferência:</strong>
  <%= @movimentacao.tranferencia %>
</p>

<p>
  <strong>Saque:</strong>
  <%= @movimentacao.saque %>
</p>

<p>
  <strong>Depósito:</strong>
  <%= @movimentacao.deposito %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @movimentacao.valor %>
</p>

<%= link_to 'Voltar', movimentacaos_path %>